# Generated by Django 5.0.4 on 2024-05-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_purchase_history_borrowinghistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowinghistory',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
